services:
  namenode:
    platform: linux/amd64
    image: apache/hadoop:3.3.6
    hostname: namenode
    ports:
      - "9870:9870"
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/hadoop/etc/hadoop"
    volumes:
      - "./hadoop_data:/opt/hadoop/hadoop_data"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9870 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: >
      bash -c "
        export HADOOP_HOME=/opt/hadoop &&
        echo '<configuration>
        <property><name>yarn.app.mapreduce.am.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.map.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.reduce.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        </configuration>' > /opt/hadoop/etc/hadoop/mapred-site.xml &&
        hdfs namenode -format -force &&
        hdfs namenode
      "

  datanode:
    platform: linux/amd64
    image: apache/hadoop:3.3.6
    hostname: datanode
    depends_on:
      namenode:
        condition: service_healthy
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/hadoop/etc/hadoop"
    volumes:
      - "./hadoop_data:/opt/hadoop/hadoop_data"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://namenode:9870 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: >
      bash -c "
        export HADOOP_HOME=/opt/hadoop &&
        echo '<configuration>
        <property><name>yarn.app.mapreduce.am.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.map.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.reduce.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        </configuration>' > /opt/hadoop/etc/hadoop/mapred-site.xml &&
        hdfs datanode
      "

  resourcemanager:
    platform: linux/amd64
    image: apache/hadoop:3.3.6
    hostname: resourcemanager
    ports:
      - "8088:8088"
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/hadoop/etc/hadoop"
    volumes:
      - "./hadoop_data:/opt/hadoop/hadoop_data"
      - "./test.sh:/opt/test.sh"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://resourcemanager:8088/cluster/cluster || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: >
      bash -c "
        export HADOOP_HOME=/opt/hadoop &&
        echo '<configuration>
        <property><name>yarn.app.mapreduce.am.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.map.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.reduce.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        </configuration>' > /opt/hadoop/etc/hadoop/mapred-site.xml &&
        yarn resourcemanager
      "

  nodemanager:
    platform: linux/amd64
    image: apache/hadoop:3.3.6
    hostname: nodemanager
    depends_on:
      resourcemanager:
        condition: service_healthy
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/hadoop/etc/hadoop"
    volumes:
      - "./hadoop_data:/opt/hadoop/hadoop_data"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://resourcemanager:8088/cluster/cluster || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: >
      bash -c "
        export HADOOP_HOME=/opt/hadoop &&
        echo '<configuration>
        <property><name>yarn.app.mapreduce.am.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.map.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.reduce.env</name>
        <value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        </configuration>' > /opt/hadoop/etc/hadoop/mapred-site.xml &&
        yarn nodemanager
      "

  java:
    platform: linux/amd64
    image: openjdk:8-jdk-alpine
    hostname: java
    volumes:
      - "./hadoop_data:/opt/hadoop/hadoop_data"
    command: >
      sh -c "apk add --no-cache bash && tail -f /dev/null"

volumes:
  hadoop_data:
