services:
  namenode:
    platform: linux/amd64
    image: apache/hadoop:3.3.6
    hostname: namenode
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      HADOOP_HOME: /opt/hadoop
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
    volumes:
      - ./shared_dir:/shared_dir
    command: |
      bash -c "
        export HADOOP_HOME=/opt/hadoop &&
        echo '<configuration>
        <property><name>yarn.app.mapreduce.am.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.map.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.reduce.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        </configuration>' > /opt/hadoop/etc/hadoop/mapred-site.xml &&
        hdfs namenode -format &&
        hdfs namenode
      "

  datanode:
    platform: linux/amd64
    image: apache/hadoop:3.3.6
    hostname: datanode
    env_file:
      - ./config
    environment:
      HADOOP_HOME: /opt/hadoop
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
    volumes:
      - ./shared_dir:/shared_dir
    command: |
      bash -c "
        export HADOOP_HOME=/opt/hadoop &&
        echo '<configuration>
        <property><name>yarn.app.mapreduce.am.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.map.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.reduce.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        </configuration>' > /opt/hadoop/etc/hadoop/mapred-site.xml &&
        hdfs datanode
      "

  resourcemanager:
    platform: linux/amd64
    image: apache/hadoop:3.3.6
    hostname: resourcemanager
    ports:
      - 8088:8088
    env_file:
      - ./config
    environment:
      HADOOP_HOME: /opt/hadoop
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
    volumes:
      - ./shared_dir:/shared_dir
      - ./test.sh:/opt/test.sh
    command: |
      bash -c "
        export HADOOP_HOME=/opt/hadoop &&
        echo '<configuration>
        <property><name>yarn.app.mapreduce.am.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.map.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.reduce.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        </configuration>' > /opt/hadoop/etc/hadoop/mapred-site.xml &&
        yarn resourcemanager
      "

  nodemanager:
    platform: linux/amd64
    image: apache/hadoop:3.3.6
    hostname: nodemanager
    env_file:
      - ./config
    environment:
      HADOOP_HOME: /opt/hadoop
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
    volumes:
      - ./shared_dir:/shared_dir
    command: |
      bash -c "
        export HADOOP_HOME=/opt/hadoop &&
        echo '<configuration>
        <property><name>yarn.app.mapreduce.am.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.map.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        <property><name>mapreduce.reduce.env</name><value>HADOOP_MAPRED_HOME=/opt/hadoop</value></property>
        </configuration>' > /opt/hadoop/etc/hadoop/mapred-site.xml &&
        yarn nodemanager
      "

  java:
    platform: linux/amd64
    image: openjdk:8-jdk-alpine
    hostname: java
    volumes:
      - ./shared_dir:/shared_dir
    command: |
      sh -c "apk add --no-cache bash && tail -f /dev/null"

volumes:
  shared-volume:
